manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: leonasdev
      url-base: https://github.com/leonasdev
  projects:
    - name: zmk
      remote: leonasdev
      revision: animated_widgets
      import: app/west.yml
  self:
    path: config
